name: MineHunt
version: 3.3.4
main: net.mcbbs.jerryzrf.minehunt.MineHunt
api-version: 1.17
authors: [ JerryZRF ]
description: 猎人游戏
website: www.mcbbs.net
softdepend: [ PlaceholderAPI ]
commands:
  minehunt:
    description: "主命令"
    aliases:
      - mh
    usage: "/minehunt help"
permissions:
  minehunt.admin:
    description: 允许使用minehunt管理员命令
    children:
      minehunt.join: true
      minehunt.start: true
      minehunt.resetcountdown: true
      minehunt.resetkit: true
      minehunt:reload: true
    default: op
  minehunt.join:
    description: 允许强制加入一开始的游戏
    default: op
  minehunt.start:
    description: 允许强制开始游戏
    default: op
  minehunt.reset:
    description: 允许重置倒计时
    default: op
  minehunt.resetkit:
    description: 允许重置职业CD
    default: op
  minehunt.reload:
    description: 允许重载配置文件
    default: op
