# 本插件版本为MossCG瞎改改出来的
# 经过JerryZRF的修改
# 下面是插件配置文件www~

#版本信息 (请勿更改)
version: 1

#本局最大玩家数
max-players: 16

#本局最小玩家数（不达到这个数量不会开局）
min-players: 2

#本局最大Runner数（这东西我基本用不到了但是还是不敢删免得出问题）
runner-max: 2

#第零阶梯玩家数量（大于等于该数量Runner会设置对应阶梯数量，下同）
#如L0Player=2 L0Hunter=1即在总玩家达到2及以上的时候，猎人数为1）
L0Player: 2

#第零阶梯逃亡者数量
L0Runner: 1

#第一阶梯玩家数量
L1Player: 6

#第一阶梯逃亡者数量
L1Runner: 2

#第二阶梯玩家数量
L2Player: 12

#第二阶梯逃亡者数量
L2Runner: 3

#第三阶梯玩家数量
L3Player: 16

#第三阶梯逃亡者数量
L3Runner: 4

#是否开局解锁指南针
CompassUnlocked: true

#是否结束游戏自动重启
AutoRestart: true

#逃亡者X轴偏移（Basic为基础偏移，Random为随机值）
#实际偏移量为（Basic+Random）
#如XBasic: 10 XRandom: 20 则实际偏移量为10+(0~20)=10~30中取一个随机数
XBasic: 5
XRandom: 10

#逃亡者Y轴偏移（Basic为基础偏移，Random为随机值）
#计算原理同上
YBasic: 5
YRandom: 10

#逃亡者警告距离
#好气哦我看了半天发现原作者把distance写成了distanceSquared
#也就是原本的是距离xyz的平方和，已修复为正常的距离（应该没问题了）
#建议合理调整方便猎人生存
WarnDistance: 50

#开局倒计时时长
Countdown: 30

#逃亡者警告消息(%wd是警告距离就是上面那个，%d是当前距离）
WarnDistanceSafe: "%wdM 内未检测到猎人"
WarnDistanceClose: "警告! 猎人正在靠近！当前距离：%dM"

#服务器名称（实际上也就结束统计的时候显示一下）
ServerName: "Example"

#游戏名称（实际上也同样就结束统计的时候显示一下）
ServerGame: "猎人游戏"

#观战玩家名字前缀
ObserverName: "[吃瓜]"

#追杀者玩家名字前缀
HunterName: "[猎人]"

#逃亡者玩家名字前缀
RunnerName: "[逃亡者]"

#等待中玩家名字前缀
WaitingName: "[等待中]"

#统计展示的击杀龙的玩家
DragonKiller: "屠龙勇士"

#统计展示的击杀逃亡者的玩家
RunnerKiller: "最佳猎人"

#统计展示的对任何实体输出伤害最多的玩家
DamageOutPut: "最佳输出"

#统计展示的受到伤害最多的玩家
DamageReceive: "最惨靶子"

#统计展示的对队友输出最多的玩家
TeamKiller: "队友杀手"

#统计展示的移动距离最多的玩家
WalkMaster: "大旅行者"

#统计展示的跳跃次数最多的玩家
JumpMaster: "蹦迪大师"

#统计展示结束后的结语
EndText1: "感谢游玩"
EndText2: "Thanks for playing!"

#开局获得的面包数
Bread: 5

#玩家到齐的倒计时
FullCountDown: 5

#私聊前缀
ChatinTeam: 
  - “#”

#游戏难度
#0 和平 || 1 简单 || 2 普通 || 3 困难
Difficult: 3

#是否更换地图
changeMap: true