name: MineHunt
version: ${project.version}
main: net.mcbbs.jerryzrf.minehunt.MineHunt
api-version: 1.17
authors: [JerryZRF]
description: 猎人游戏
website: www.mcbbs.net
softdepend:
  - PlaceholderAPI
commands:
  minehunt:
    description: "主命令"
    aliases:
      - mh
    usage: "/minehunt forcestart||players||copyright||resetcountdown||join {team"
permissions:
  minehunt.*:
    description: 允许使用minehunt命令
    children:
      minehunt.join: true
      minehunt.start: true
      minehunt.reset: true
    default: op
  minehunt.join:
    description: 允许强制加入一开始的游戏
    default: op
  minehunt.start:
    description: 允许强制开始游戏
    default: op
  minehunt.reset:
    description: 允许重置倒计时
    default: op
